sudo: false
language: rust

matrix:
  include:
    - rust: 1.31.0
    - rust: stable
    - rust: beta
    - rust: nightly
      script:
        - cargo test --verbose
        - rm target/debug/deps/libderive_new-*.so
        - cargo test --verbose --manifest-path testcrate/Cargo.toml

env:
  global:
    - RUST_BACKTRACE=1

script:
  - cargo test --verbose
